// <auto-generated />
namespace SISControlAPI.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class apiControl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(apiControl));
        
        string IMigrationMetadata.Id
        {
            get { return "202006201547069_apiControl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
